# Generated by Django 5.0.6 on 2024-05-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
